version: '3'

networks:
  prometheus-net:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - prometheus-net
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerting-rules.yml:/etc/prometheus/alerting-rules.yml

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:0.10.0
    container_name: prometheus-nginx-exporter
    # env_file:
    #   .env
    command:
      - -nginx.scrape-uri=http://nginx:8080/stub_status
    # expose: 
      # - 9113
    ports:
      - "9113:9113"
    networks:
      - prometheus-net
    depends_on:
      - prometheus
      - nginx

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - prometheus-net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    networks:
      - prometheus-net

  express:
    image: node:18
    container_name: express-server
    working_dir: /app
    volumes:
      - ./express:/app
    command: npm start
    ports:
      - "3000:3000"
    # depends_on:
    #   - alertmanager
    networks:
      - prometheus-net


# Use this container for testing
  # curl-container:
  #   image: alpine:latest
  #   command: sh -c "apk --no-cache add curl && sleep infinity"
  #   networks:
  #     - prometheus-net