# my global config
global:
  scrape_interval:     3s # Scrape interval. Default is every 1 minute.
  evaluation_interval: 3s # Evaluate rules .The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).


# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alerting-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'  # Alert manager service url (check docker-compose) and port

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'express-server'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['express-server:3000']
  - job_name: 'nginx'
    metrics_path: '/metrics'
    static_configs:
      # - targets: ['nginx:80']
      - targets: ['nginx-prometheus-exporter:9113']
